NurseManagementWeb/NurseManagement/Controllers/HospitalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NurseManagement.Models;
using NurseManagement.Service;

namespace NurseManagement.Controllers
{
    public class HospitalController : Controller
    {
        private readonly HospitalService _hospitalService;
        private readonly string _prefix;

        public HospitalController(HospitalService hospitalService)
        {
            _hospitalService = hospitalService;
            _prefix = "hospital";
        }
        public IActionResult Index()
        {
            var result = _hospitalService.List(_prefix).ToList();
            return View(result);
        }

        public IActionResult Detail(Guid id)
        {
            var result = _hospitalService.Get($"{_prefix}/{id}");
            return View(result);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Hospital hospital)
        {
            var result = _hospitalService.Post($"{_prefix}", hospital);
            if (result == true)
                return RedirectToAction("Index", _hospitalService.List(_prefix));
            return View("Create", hospital);
        }

        public IActionResult Edit(Guid id)
        {
            var result = _hospitalService.Get($"{_prefix}/{id}");
            return View(result);
        }

        [HttpPost]
        public IActionResult Edit(Guid id, Hospital hospital)
        {
            var result = _hospitalService.Put($"{_prefix}/{id}", hospital);
            if (result == true)
                return RedirectToAction("Index", _hospitalService.List(_prefix));
            return View("Edit", hospital);
        }

        public JsonResult Delete(int Id, Nurse nurse)
        {
            bool result = false;
            try
            {
                var resultado = _hospitalService.Delete($"{_prefix}/{nurse.Id}");
                result = true;
            }
            catch (Exception dex)
            {
                return Json(new { success = false, responseText = dex.Message });
            }
            return Json(new { success = false, responseText = "Registro Deletado Com Sucesso" });
        }
    }
}

NurseManagementWeb/NurseManagement/Controllers/NurseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NurseManagement.Models;
using NurseManagement.Service;

namespace NurseManagement.Controllers
{
    public class NurseController : Controller
    {
        private readonly HospitalService _hospitalService;
        private readonly NurseService _nurseService;
        private readonly string _prefix;
        private readonly string _prefixHospital;

        public NurseController(NurseService nurseService)
        {
            _nurseService = nurseService;
            _prefix = "nurse";
            _prefixHospital = "hospital";

        }

        public IActionResult Index()
        {
            var result = _nurseService.List(_prefix).ToList();
            return View(result);
        }

        public IActionResult Detail(Guid id)
        {
            var result = _nurseService.Get($"{_prefix}/{id}");
            return View(result);
        }

        public IActionResult Create()
        {
            ListHospital();
            return View();
        }

        [HttpPost]
        public IActionResult Create(Nurse nurse)
        {
            var result = _nurseService.Post($"{_prefix}", nurse);
            if (result == true)
                return RedirectToAction("Index", _nurseService.List(_prefix));
            return View("Create", nurse);
        }

        public IActionResult Edit(Guid id)
        {
            ListHospital();
            var result = _nurseService.Get($"{_prefix}/{id}");
            return View(result);
        }

        [HttpPost]
        public IActionResult Edit(Guid id, Nurse nurse)
        {
            var result = _nurseService.Put($"{_prefix}/{id}", nurse);
            if (result == true)
                return RedirectToAction("Index", _nurseService.List(_prefix));
            return View("Edit", nurse);
        }

        public JsonResult Delete(int Id, Nurse nurse)
        {
            bool result = false;
            try
            {
                var resultado = _nurseService.Delete($"{_prefix}/{nurse.Id}");
                result = true;
            }
            catch (Exception dex)
            {
                return Json(new { success = false, responseText = dex.Message });
            }
            return Json(new { success = false, responseText = "Registro Deletado Com Sucesso" });
        }

        public void ListHospital()
        {
            ViewBag.Hospital = "";
            var result = _nurseService.ListHospital(_prefixHospital).ToList();
            ViewBag.Hospital = result;
        }
    }
}

NurseManagementWeb/NurseManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gerenciamento de Enfemeiro</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />

        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
        <link href="~/css/site.css" rel="stylesheet" />
        <script src="~/modal/DeleteModal.js"></script>
        <link rel="stylesheet" href="sweetalert2/dist/sweetalert2.min.css">
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container text-primary">
            <div class="navbar-header">
                <button  type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Gerenciamento de Enfemeiro</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav button">
                    <li><a asp-area="" asp-controller="Hospital" asp-action="Index">Cadastro de Hospitais</a></li>
                    <li><a asp-area="" asp-controller="Nurse" asp-action="Index">Cadastro de Enfermeiros</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <div></div>
        <footer class="text-center well alert-success">
            <p>&copy; 2020 - Gerencimanto de Enfemeiro</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/Mascaras/jquery.mask.js" asp-append-version="true"></script>
        <script src="~/Mascaras/Mascaras.js" asp-append-version="true"></script>
        <script src="~/js/controllerDataTable.js" asp-append-version="true"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>